#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <FreeRTOS.h>
#include "FreeRTOS_CLI.h"
#include "task.h"
#include "cli_commands.h"

static BaseType_t prvTaskStatsCommand( char *pcWriteBuffer,
                                          size_t xWriteBufferLen,
										  const char *pcCommandString )
{
    static BaseType_t state = 0;

    if (!state){
        /* For simplicity, this function assumes the output buffer is large enough
        to hold all the text generated by executing the vTaskList() API function,
        so the xWriteBufferLen parameter is not used. */
        char *head = "Name		State  Priority  Stack  Number\n\r";
        ( void ) xWriteBufferLen;

        /* pcWriteBuffer is used directly as the vTaskList() parameter, so the table
        generated by executing vTaskList() is written directly into the output
        buffer. */
        strcpy(pcWriteBuffer, head);
        vTaskList( &pcWriteBuffer[strlen(head)]);

        /* The entire table was written directly to the output buffer.  Execution
        of this command is complete, so return pdFALSE. */
        state = 1;
        return pdTRUE;
    }else{
        state = 0;
        strcpy(pcWriteBuffer, "\n\r");
        return pdFALSE;
    }
}


static const CLI_Command_Definition_t xTasksCommand =
{
    "tasks",
	DEFAULT_HELP_COLOR"tasks"ANSI_COLOR_RESET": Lists all the installed tasks\r\n\r\n",
	prvTaskStatsCommand,
    0
};

static BaseType_t prvEchoCommand(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString)
{
    (void)pcWriteBuffer;
    (void)xWriteBufferLen;
    (void)pcCommandString;

	sprintf(pcWriteBuffer, "%s\r\n", pcCommandString + 5);
   	return pdFALSE;
}

static const CLI_Command_Definition_t xEchoCommand =
{
    "echo",
	DEFAULT_HELP_COLOR"echo"ANSI_COLOR_RESET": Will send back what we received\r\n\r\n",
	prvEchoCommand,
    -1
};

BaseType_t prvColorCommand(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString)
{
	(void)pcWriteBuffer;
	(void)xWriteBufferLen;
	(void)pcCommandString;

	uint32_t foreground, background, pLen;

	foreground = atoi(FreeRTOS_CLIGetParameter(pcCommandString, (UBaseType_t)1, (BaseType_t*)&pLen));
	background = atoi(FreeRTOS_CLIGetParameter(pcCommandString, (UBaseType_t)2, (BaseType_t*)&pLen));

	if (background == foreground && background != 0)
	{
		sprintf(pcWriteBuffer, "Cannot set both background and foreground to one color");
		return pdFALSE;
	}

	char output[18] = {0};

	switch(foreground) {
		case 1:
			strcat(output, ANSI_COLOR_FOREGROUND_RED);
			break;
		case 2:
			strcat(output, ANSI_COLOR_FOREGROUND_GREEN);
			break;
		case 3:
			strcat(output, ANSI_COLOR_FOREGROUND_YELLOW);
			break;
		case 4:
			strcat(output, ANSI_COLOR_FOREGROUND_BLUE);
			break;
		case 5:
			strcat(output, ANSI_COLOR_FOREGROUND_MAGENTA);
			break;
		case 6:
			strcat(output, ANSI_COLOR_FOREGROUND_CYAN);
			break;
		case 7:
			strcat(output, ANSI_COLOR_FOREGROUND_WHITE);
			break;
		case 8:
			strcat(output, ANSI_COLOR_FOREGROUND_BLACK);
			break;
		default:
			strcat(output, ANSI_COLOR_FOREGROUND_DEFAULT);
			break;
	}

	switch(background) {
		case 1:
			strcat(output, ANSI_COLOR_BACKGROUND_RED);
			break;
		case 2:
			strcat(output, ANSI_COLOR_BACKGROUND_GREEN);
			break;
		case 3:
			strcat(output, ANSI_COLOR_BACKGROUND_YELLOW);
			break;
		case 4:
			strcat(output, ANSI_COLOR_BACKGROUND_BLUE);
			break;
		case 5:
			strcat(output, ANSI_COLOR_BACKGROUND_MAGENTA);
			break;
		case 6:
			strcat(output, ANSI_COLOR_BACKGROUND_CYAN);
			break;
		case 7:
			strcat(output, ANSI_COLOR_BACKGROUND_WHITE);
			break;
		case 8:
			strcat(output, ANSI_COLOR_BACKGROUND_BLACK);
			break;
		default:
			strcat(output, ANSI_COLOR_BACKGROUND_DEFAULT);
			break;
	}
	strcat(output, CSI"2J"CSI"H");
	sprintf(pcWriteBuffer, "%s\r\n", output);
	return pdFALSE;
}

static const CLI_Command_Definition_t xColorCommand =
{
		"color",
		DEFAULT_HELP_COLOR"color"ANSI_COLOR_RESET":\r\n\tchanges color background and foreground\r\n"
		"\tusage: color [foreground color (font)] [background color]\r\n"
		"\texample: color 5 6\r\n"
		"\tresults setting font to magenta and background to cyan\r\n"
		"\tAvailabale colors:\r\n"
		"\t\t0: "ANSI_COLOR_FOREGROUND_DEFAULT"default"ANSI_COLOR_RESET
		"  1: "ANSI_COLOR_FOREGROUND_RED"red"ANSI_COLOR_RESET
		"  2: "ANSI_COLOR_FOREGROUND_GREEN"green"ANSI_COLOR_RESET
		"  3: "ANSI_COLOR_FOREGROUND_YELLOW"yellow"ANSI_COLOR_RESET
		"  4: "ANSI_COLOR_FOREGROUND_BLUE"blue"ANSI_COLOR_RESET
		"  5: "ANSI_COLOR_FOREGROUND_MAGENTA"magenta"ANSI_COLOR_RESET
		"  6: "ANSI_COLOR_FOREGROUND_CYAN"cyan"ANSI_COLOR_RESET
		"  7: "ANSI_COLOR_FOREGROUND_WHITE"white"ANSI_COLOR_RESET
		"  8: "ANSI_COLOR_BACKGROUND_WHITE ANSI_COLOR_FOREGROUND_BLACK"black\r\n"ANSI_COLOR_RESET
		"\tNote:\r\n\t\tIf parameter is not present then it set to default\r\n\r\n",
	prvColorCommand,
    -1
};

BaseType_t CLI_install_commands(void){
	if(pdPASS == FreeRTOS_CLIRegisterCommand( &xTasksCommand )){
		if(pdPASS == FreeRTOS_CLIRegisterCommand( &xEchoCommand )){
			if(pdPASS == FreeRTOS_CLIRegisterCommand( &xColorCommand )){
				return pdPASS;
			}
		}
	}
	return pdFAIL;
}


