#ifndef _CLI_COMMANDS_H
#define _CLI_COMMANDS_H

#include <FreeRTOS.h>

#define CSI					"\x1b["	// Control Sequence Introducer
//#ifdef ANSI_COLORS

// font colors
#define ANSI_COLOR_FOREGROUND_BLACK		CSI"30m"
#define ANSI_COLOR_FOREGROUND_RED		CSI"31m"
#define ANSI_COLOR_FOREGROUND_GREEN		CSI"32m"
#define ANSI_COLOR_FOREGROUND_YELLOW	CSI"33m"
#define ANSI_COLOR_FOREGROUND_BLUE		CSI"34m"
#define ANSI_COLOR_FOREGROUND_MAGENTA	CSI"35m"
#define ANSI_COLOR_FOREGROUND_CYAN		CSI"36m"
#define ANSI_COLOR_FOREGROUND_WHITE		CSI"37m"
#define ANSI_COLOR_FOREGROUND_DEFAULT	CSI"39m"

//background colors
#define ANSI_COLOR_BACKGROUND_BLACK		CSI"40m"
#define ANSI_COLOR_BACKGROUND_RED		CSI"41m"
#define ANSI_COLOR_BACKGROUND_GREEN		CSI"42m"
#define ANSI_COLOR_BACKGROUND_YELLOW	CSI"43m"
#define ANSI_COLOR_BACKGROUND_BLUE		CSI"44m"
#define ANSI_COLOR_BACKGROUND_MAGENTA	CSI"45m"
#define ANSI_COLOR_BACKGROUND_CYAN		CSI"46m"
#define ANSI_COLOR_BACKGROUND_WHITE		CSI"47m"
#define ANSI_COLOR_BACKGROUND_DEFAULT	CSI"49m"

#define ANSI_COLOR_RESET    			CSI"0m"
#define DEFAULT_HELP_COLOR ANSI_COLOR_FOREGROUND_CYAN
#define DEFAULT_ACCENT_COLOR ANSI_COLOR_FOREGROUND_GREEN

BaseType_t CLI_install_commands(void);

#endif
